modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/botarium/issues"

[[mods]]
modId = "botarium"
version = "${version}"
displayName = "Botarium"
displayURL = "https://modrinth.com/mod/botarium"
logoFile = "icon.png"
authors = "CodexAdrian"
credits = "ThatGravyBoat, MsRandom1 (Ashley), Alex Nijjar"
description = "A crossplatform API for devs that makes transfer and storage of items, fluids and energy easier, as well as some other helpful things"

[[dependencies.botarium]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botarium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
