modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/Common-Storage-Lib/issues"

[[mods]]
modId = "common_storage_lib_lookup"
version = "${version}"
displayName = "Common Storage Lib: Lookup"
displayURL = "https://modrinth.com/mod/botarium"
authors = "CodexAdrian"
description = "Abstraction for mod loader's item/entity/block API provider system (Capabilities/ApiLookup)"

[[dependencies.common_storage_lib_lookup]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.common_storage_lib_lookup]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"