modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/Botarium/issues"

[[mods]]
modId = "common_storage_lib_core"
version = "${version}"
displayName = "Common Storage Lib: Core"
displayURL = "https://modrinth.com/mod/botarium"
authors = "CodexAdrian"
description = "Abstraction of the mod loader's resource storage system, allowing for easy access to items, fluids and energy"

[[dependencies.common_storage_lib]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.common_storage_lib]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"