modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/Botarium/issues"

[[mods]]
modId = "botarium_byte_codecs"
version = "${version}"
displayName = "Botarium Byte Codecs"
displayURL = "https://modrinth.com/mod/Botarium"
authors = "CodexAdrian"
description = "Byte Codecs for Botarium"

[[dependencies.botarium]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botarium]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"